const guardiansToBeReplaced = [
    'AMZ  Microfinance Institution PLc.',
    'Bangkok  Bank Public Company Limitedm Cambodia Branch',
    'BANK  FOR INVESTMENT&DEVELOPMENT OF CAMBODIA Plc.',
    'CAMBODIAN  COMMERCIAL BANK PLC.',
    'Heng  Feng Commercial Bank',
    'Hong  Leong Bank (Cambodia) Plc',
    'Hong  Leong Bank (Cambodia) PLc.',
    'JC  FINANCE PLC.',
    'LCH  Microfinance Plc',
    'Leng  Navatra Capital Plc',
    'Sathapana  Bank Plc',
    'Shinhan  Bank (Cambodia) PLc.',
    'Vattanac  Bank',
    'CAMMA  MICROFINANCE LIMITED',
    'Corich  Microfinance PLC.',
    'FOREIGN  TRADE BANK OF CAMBODIA',
    'G  B MFI',
    'NongHyup  Finance',
    'PANDA  Commercial Bank Plc.',
    'Paragon  University',
    'PRINCE  BANK PLC.',
    'Right  Smart Finance',
    'Rolya  Plc.',
    ''
]